title: ChatApp
description: تطبيق مراسلة فورية مع مكالمات صوتية ومرئية
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages settings
baseurl: ""
url: "https://your-username.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files
exclude:
  - README.md
  - DEPLOY.md
  - .gitignore
